version: '3.3'
services:
  app:
    image: node:14.18-alpine
    container_name: "typeorm-app"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    command: npm start
    ports:
      - 3100:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: "admin"
      DB_PASSWORD: "adminpw"
      DB_DATABASE: "typeorm"
    links:
      - db
  db:
    image: "mysql:8.0.26"
    container_name: "typeorm-db"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"


